/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Railway;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rahul Vijayan
 */
public class Reservation extends javax.swing.JFrame {

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
        Connect();
        LoadStartPlace();
        LoadDestinationPlace();
    }
    
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public void Connect()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/railway_reservation_system","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Train_Details.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    
    
    
    public void LoadStartPlace()
    {
        try {
            pst = con.prepareStatement("SELECT startPlace From train");
            rs = pst.executeQuery();
            start.removeAllItems();
            
            while(rs.next())
            {
                start.addItem(rs.getString(1));
            }
            
            
        } catch (Exception e) 
        {
            e.printStackTrace();
        }
        
    }
    
    
    public void LoadDestinationPlace()
    {
        try {
            pst = con.prepareStatement("SELECT destinationPlace From train");
            rs = pst.executeQuery();
            destination.removeAllItems();
            
            while(rs.next())
            {
                destination.addItem(rs.getString(1));
            }
            
            
        } catch (Exception e) 
        {
            e.printStackTrace();
        }
        
    }
    
    
    public void load()
    {
        String StartPlace = start.getSelectedItem().toString();
        String DestinationPlace = destination.getSelectedItem().toString();
        
        
        try {
            pst = con.prepareStatement("SELECT * FROM train where startPlace = ? and destinationPlace = ?");
            
            pst.setString(1, StartPlace);
            pst.setString(2, DestinationPlace);
            
            rs = pst.executeQuery();
            
            
            if(rs.next() == true)
            {
                trainid.setText(rs.getString(1));
                trainname.setText(rs.getString(2));
                price.setText(rs.getString(5));
            }
            
            else
            {
                JOptionPane.showMessageDialog(this, "Record not Found!!!!!!!");
            }
            
            
        } catch (Exception e) {
          e.printStackTrace();
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        start = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        trainid = new javax.swing.JTextField();
        trainname = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        ticket = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("RESERVATION");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 40, 420, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 0));
        jLabel3.setText("Passenger ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 150, 160, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 0));
        jLabel4.setText("Start Place");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 210, 140, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Destination Place");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 250, 190, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 255, 0));
        jLabel6.setText("Train No");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(320, 310, 110, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 0));
        jLabel7.setText("Train Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 360, 150, 20);

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Price");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 400, 100, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 255, 0));
        jLabel9.setText("Date");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 450, 70, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 255, 0));
        jLabel10.setText("Number of Tickets");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 500, 200, 20);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 0));
        jLabel12.setText("Total");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 540, 90, 40);

        userid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(userid);
        userid.setBounds(570, 150, 230, 30);

        start.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(start);
        start.setBounds(570, 196, 230, 28);

        destination.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(destination);
        destination.setBounds(570, 250, 230, 30);

        trainid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(trainid);
        trainid.setBounds(570, 300, 230, 30);

        trainname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(trainname);
        trainname.setBounds(570, 350, 230, 30);

        price.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(price);
        price.setBounds(570, 400, 230, 30);

        ticket.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ticketKeyPressed(evt);
            }
        });
        getContentPane().add(ticket);
        ticket.setBounds(570, 490, 230, 30);

        total.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(total);
        total.setBounds(570, 540, 230, 30);
        getContentPane().add(date);
        date.setBounds(570, 440, 230, 30);

        jButton1.setBackground(new java.awt.Color(51, 51, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Reserve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(680, 610, 220, 80);

        jButton2.setBackground(new java.awt.Color(51, 51, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(900, 210, 120, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rahul Vijayan\\Documents\\NetBeansProjects\\Railway Reservation System\\images\\2.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, -50, 1430, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String Passenger = userid.getText();
        String StartPlace = start.getSelectedItem().toString();
        String DestinationPlace = destination.getSelectedItem().toString();
        String TrainID = trainid.getText();
        String TrainName = trainname.getText();
        String Price = price.getText();
        SimpleDateFormat date_form = new SimpleDateFormat("dd-MM-yyyy");
        String Date = date_form.format(date.getDate());
        String Ticket = ticket.getText();
        String Total = total.getText();
        
        
        try {
            pst = con.prepareStatement("insert into reservation(id,startPlace,destinationPlace,trainId,trainName,Price,Date,Ticket,Total)values(?,?,?,?,?,?,?,?,?)");
                    
            pst.setString(1, Passenger);
            pst.setString(2, StartPlace);
            pst.setString(3, DestinationPlace);
            pst.setString(4, TrainID);
            pst.setString(5, TrainName);
            pst.setString(6, Price);
            pst.setString(7, Date);
            pst.setString(8, Ticket);
            pst.setString(9, Total);
            
            
            int k = pst.executeUpdate();
            
            if(k == 1)
            {
                JOptionPane.showMessageDialog(this, "Ticket Reserved Successfully");
            }
            
            else
            {
                JOptionPane.showMessageDialog(this, "Ticket Reservation Failed");
            }
                    
                    } catch (SQLException ex) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ticketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ticketKeyPressed
        // TODO add your handling code here:
        
        int amt,tckt,tot;
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            amt = Integer.parseInt(price.getText());
            tckt = Integer.parseInt(ticket.getText());
            
            tot = amt * tckt;
            
            total.setText(String.valueOf(tot));
            
        }
        
    }//GEN-LAST:event_ticketKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> start;
    private javax.swing.JTextField ticket;
    private javax.swing.JTextField total;
    private javax.swing.JTextField trainid;
    private javax.swing.JTextField trainname;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
